### ISSUE TITLE
How to save R-squared and adjusted R-squared?

### ISSUE THREAD

**Issue by shibaoliu** [mdroste/stata-regressby#3]
Super powerful command for group regression. Did anyone try to save R-squared and adjusted R-squared for each group? How to process under regressby?

Thanks!

**Comment by mdroste** [comment]
Hey, thanks! I haven't implemented any regression diagnostics because you can usually do them with some post-processing and a few -egen/gegen, by(group)- commands (e.g. compute SST and SSR within each group for R2). It would be nice to add, but I have no plans to do this before going on the job market, so I'm going to close this for now.
